FROM continuumio/miniconda
MAINTAINER Paolo Di Tommaso <paolo.ditommaso@gmail.com>

RUN conda install -y -c r r-base 
 
RUN apt-get update && apt-get -y install build-essential ttf-dejavu  

RUN conda config --add channels defaults \
 && conda config --add channels conda-forge \
 && conda config --add channels bioconda \
 && conda install -y picard=2.9 bwa=0.7.15 fastqc=0.11.5 sambamba=0.6.6 

RUN conda install -y tabix
